### ISSUE TITLE
Web服务无法启动，麻烦帮忙看一下。

### ISSUE THREAD

**Issue by qfzy1233** [myhhub/InStock#6]
感谢作者的分享，工作脚本调试后可以正常运行了，但是web可视化脚本无法运行，浏览器界面显示：localhost 已拒绝连接。运行日志如下：
Active code page: 65001
Traceback (most recent call last):
  File "D:\InStock-master\instock\web\main.py", line 26, in <module>
    import instock.web.dataIndicatorsHandler as dataIndicatorsHandler
  File "D:\InStock-master\instock\web\dataIndicatorsHandler.py", line 9, in <module>
    import instock.core.kline.visualization as vis
  File "D:\InStock-master\instock\core\kline\visualization.py", line 8, in <module>
    from bokeh.plotting import figure
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\plotting\__init__.py", line 22, in <module>
    from . import figure as _figure ; _figure
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\plotting\figure.py", line 40, in <module>
    from ..models import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\models\__init__.py", line 35, in <module>
    from .annotations import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\models\annotations\__init__.py", line 23, in <module>
    from . import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\bokeh\models\annotations\annotation.py", line 25, in <module>
    from ...core.properties import Instance, InstanceDefault, Override
ImportError: cannot import name 'InstanceDefault' from 'bokeh.core.properties' (C:\ProgramData\Anaconda3\lib\site-packages\bokeh\core\properties.py)
------Web服务已启动，请不要关闭------
访问地址 : http://localhost:9999/
Press any key to continue . . .

已经尝试过1.启用系统Internet Information 功能；
                   2.关闭系统防火墙；
                   3.修改端口号；
                   4.相应端口ping不通。

**Comment by qfzy1233** [comment]
stock_web.log内容为空
